FROM ubuntu:14.04

RUN apt-get update -y

RUN apt-get install -y python-setuptools get telnet curl

RUN easy_install pip

ADD . /src
WORKDIR /src
RUN pip install Flask
EXPOSE 5000
CMD ["python", "entry.py"]